### ISSUE TITLE
F6 menu

### ISSUE THREAD

**Issue by Robin201492** [matsn0w/MISS-ELS#105]
hello I cant open the F5 and f6 menu

**Comment by matsn0w** [comment]
Please provide more info... What do you mean with 'the menu'?

Random guess: [this](https://github.com/matsn0w/MISS-ELS/issues/63) might be your problem.

**Comment by Robin201492** [comment]
I can´t open the job menu in els cars

**Comment by matsn0w** [comment]
That's not enough info... What menu? Did you read the issue I linked?

**Comment by Robin201492** [comment]
the menu from the esx_policejob and from the other esx jobs

**Comment by Robin201492** [comment]
and we can´t use the arrow down key

**Comment by matsn0w** [comment]
> the menu from the esx_policejob and from the other esx jobs

Ok. I'm not familiar with ESX, but I'm suspecting that it's a similar issue as [this](https://github.com/matsn0w/MISS-ELS/issues/63).

> and we can´t use the arrow down key in els vehicles
That's because it's mapped to the hazard lights. You can change the keybind in the `config.lua` file (or even disable indicators).

**Comment by matsn0w** [comment]
Closed for inactivity.
