### ISSUE TITLE
Lights not working

### ISSUE THREAD

**Issue by KezzaHPRPC** [matsn0w/MISS-ELS#121]
**Describe the bug**
After adding more VCF files to the ELS the lights dont work properly, only one side flickers and the other stays on. this has happened on multiple files

**To Reproduce**

**Expected behavior**
after adding the VCF the lights should work like the rest, its light ive hit a limit and i cant add anymore files? 

**Screenshots**
If applicable, add screenshots to help ex

https://user-images.githubusercontent.com/108136516/175546812-b6bf2bb0-c55a-4c09-9425-0ea93c5d67d8.mov

plain your problem.

**Additional context**
FiveM build: 2545
MISS ELS version: 2.1.1

**Comment by JustinRijsdijk** [comment]
Could you perhaps drop your VCF file here too? :P

**Comment by JustinRijsdijk** [comment]
well this is weird indeed, XML looks fine. Are there any console errors (server or client side)?

**Comment by matsn0w** [comment]
Are you sure the extra's in the VCF correspond to the vehicle's extra's correctly? Have your created the pattern yourself or have you copied a random XML file?

**Comment by matsn0w** [comment]
Closed for inactivity.
