### ISSUE TITLE
Lights not working and are broken!

### ISSUE THREAD

**Issue by FizzGamingJR** [matsn0w/MISS-ELS#123]
**Describe the bug**
Hello, I recently added MISS-ELS to my server with the hope that it will fix the issue with Onesync-Infinity.
After adding it, all of my Emergency Vehicles lights seemed to have stopped working correctly, upon spawning the car the lights were in a static state, and trying to turn the lights on and off will only keep the lights off with nothing apart from bleeps and "999 mode activated" voice.
As this may be important for the fix, my sirens also work as intended whenever the car thinks the lights are on.

Listed under the 'Screenshots' section are two images, first being the state the car was in after just spawning it, and the second being the state it was in after turning the lights on and off multiple times.

Listed below is a txt document which is the VCF file of the car in those images in-case I missed something, this VCF code was previously used in the original script of this fork so I don't believe I need to change it?

[skodavcf.txt](https://github.com/matsn0w/MISS-ELS/files/9149799/skodavcf.txt)

**To Reproduce**
1. Spawn ELS car.
2. Try lights.

**Expected behavior**
Lights to turn on as intended.

**Screenshots**
1st:
![Screenshot_1](https://user-images.githubusercontent.com/28313136/179984135-5c6e6e4c-cd52-47cf-beeb-8bb004c3f723.png)

2nd:
![Screenshot_2](https://user-images.githubusercontent.com/28313136/179984159-71da581f-9a10-45a0-814d-7048cc835465.png)

**Additional context**
FiveM build: Unknown
MISS ELS version: 2.1.1

**Comment by matsn0w** [comment]
Hey, thank you for your extensive description! 

Your VCF will definitely not work with this version of ELS. I advise you to rewrite a new configuration for each vehicle. Yes - that is a lot of work, but it's worth it!

Tip: use the Configurator to generate the VCF file if you're not comfortable with code. Also take a look at the documentation for a better understanding of all possibilities.

**Comment by FizzGamingJR** [comment]
> 

Oh god, thank you for the reply lmao.
The configurator is one of the best layed out programs I've seen in this industry so I don't think I'll have 'many' issues with it lol.
I have attempted to use it previously but there is a lot of sections in my VCF that is not in the configurator, for these sections should I just leave them out?

**Comment by matsn0w** [comment]
You can throw your old VCF's away. MISS ELS has a completely different system ;)
