### ISSUE TITLE
Siren comes on with lights on some vehicles??

### ISSUE THREAD

**Issue by PapiCheesecake** [matsn0w/MISS-ELS#131]
On a select few of my ELS vehicles when you enable the ELS Lights with "Q" the siren will also activate, however this isn't the same for all of them? The majority work as intended.

Reproducing is dead easy, hit "Q" and if its broken both lights and sirens come on instead of just the lights.
Video:
X5s, Volvo, Skoda are working normally - Peugeot Van, Astra, Mondeo are not
https://streamable.com/qo4xi3

**Comment by PapiCheesecake** [comment]
Edit: All ELS patterns have been made with https://matsn0w.github.io/MISS-ELS/ in the same style so idk why this happens

**Comment by matsn0w** [comment]
Okay, thanks for reporting this issue! Can you please provide the XML for 1) a vehicle with the problem and 2) a vehicle without the problem?

Another idea: are both cars flagged as emergency vehicle in the `vehicles.meta` file?

**Comment by PapiCheesecake** [comment]
Both are Flagged and Classified as an emergency vehicle.

NOT WORKING - [PTVAN.zip](https://github.com/matsn0w/MISS-ELS/files/10520920/PTVAN.zip)
WORKING - [X5.zip](https://github.com/matsn0w/MISS-ELS/files/10520923/X5.zip)

**Comment by PapiCheesecake** [comment]
> Okay, thanks for reporting this issue! Can you please provide the XML for 1) a vehicle with the problem and 2) a vehicle without the problem?
> 
> Another idea: are both cars flagged as emergency vehicle in the `vehicles.meta` file?

IVE FIXED IT!!!!!!!

So, 
The issue seems to be cause by default GTA settings. This being audio hashes. To fix this issue go to your vehicles.meta file and locate:
      <handlingId>NAME</handlingId>
and
      <audioNameHash>NAME</audioNameHash>

As is turns out some police vehicle hashes will come on with Q and not with ALT. From my little research "policet" and "police2" have this issue. 

HOW TO FIX:
Have your <audioNameHash>NAME</audioNameHash> set as something similar to the actual police vehicles in GTA, E.G. "speedo" instead of "policet".

**Comment by matsn0w** [comment]
Strange. But glad you fixed it!
