### ISSUE TITLE
999 mode (ear rape)

### ISSUE THREAD

**Issue by PapiCheesecake** [matsn0w/MISS-ELS#133]
Your casually driving around the city and a car goes flying past you so you whack on your lights just to be EARAPED BY "999 MODE ACTIVATED".

Any chance you could add a way to configure the sound. Or where the file is so i can edit the file so its quieter. Thank you!

**Comment by matsn0w** [comment]
You can disable it in the VCF. See https://github.com/matsn0w/MISS-ELS/blob/main/docs/vcf.md#sounds-sounds.

Otherwise, you can indeed change the audio file. You can find it [here](resource/html/sounds/999mode.ogg).
