### ISSUE TITLE
Lighting not working after upgrade to v2.1.1

### ISSUE THREAD

**Issue by ShadowGaming95** [matsn0w/MISS-ELS#134]
myself and my dev have got the script working after updating from V2.0.0 after syncing issues but now our lights don't work. the sirens and 999 mode all do what is expected but no lighting.

Is this something that may be missing? or something in one of the VCF's? i did try remaking it using your creator but that one didn't work either

**Additional context**
FiveM build: 2699
MISS ELS version: 2.1.1

**Comment by matsn0w** [comment]
Closed for inactivity.
