### ISSUE TITLE
Extras not resetting when spawning ELS vehicle

### ISSUE THREAD

**Issue by Magnemice** [matsn0w/MISS-ELS#136]
Every time I spawn a vehicle the extras don't reset pretty anoying

![FiveM® by Cfx re - Oost-Dijk RP Test Server 21_03_2023 13_10_37](https://user-images.githubusercontent.com/65012805/226602107-c6af29b2-8cba-4f17-9136-cb4729973d37.png)

**Comment by matsn0w** [comment]
Hey @Magnemice, thanks for reporting!

Unfortunately, this is something MISS ELS can't fix for you. Some spawners randomly set some extra's. MISS ELS can't now which extra's to reset. Resetting everything would mean that non-ELS extra's would also disappear.

**Comment by Magnemice** [comment]
> Hey @Magnemice, thanks for reporting!
> 
> Unfortunately, this is something MISS ELS can't fix for you. Some spawners randomly set some extra's. MISS ELS can't now which extra's to reset. Resetting everything would mean that non-ELS extra's would also disappear.

Oh alright also there is this weird kind of flickering that happens when you have the lights on I think its because of the flash duration
