### ISSUE TITLE
Something went wrong! Couldn't fetch latest version. Status: 403

### ISSUE THREAD

**Issue by Magnemice** [matsn0w/MISS-ELS#137]
Something went wrong! Couldn't fetch latest version. Status: 403

Getting this error in my console. Also the Extras menu doesnt work I have to restart the script after a server retart before it works

**Comment by matsn0w** [comment]
Hey, is this still an issue? It might have been due to some problem at GitHub at the time. Sorry for my late response!

**Comment by matsn0w** [comment]
Closed for inactivity.
