### ISSUE TITLE
(table expected, got nil)

### ISSUE THREAD

**Issue by Valtterie** [matsn0w/MISS-ELS#138]
**Describe the bug**
Don't know if this is a problem for the script because it works. The only thing is that the extra's menu only works after restart the script. is also changed the name of the 999 mode to disable it. didn't have much time to do it the correct way so fixed it like that. further i have changed some keybinds but that's al. the rest is stock.

**Screenshots**
https://i.imgur.com/knY5FYG.png

**Additional context**
FiveM build: 6356
MISS ELS version: 2.1.1

**Comment by matsn0w** [comment]
Hey, can you please provide your `Config.lua` file?

**Comment by matsn0w** [comment]
Closed for inactivity.
