### ISSUE TITLE
NativeUI menu

### ISSUE THREAD

**Issue by evilstriker** [matsn0w/MISS-ELS#141]
The nativeUI menu doesn't work onjoin weirdly enough only if I restart the script. I decided to add more configuarble keys to control the extra's there. Let me know if you wanna push that in.

**Comment by matsn0w** [comment]
Hi! You can try using the `develop` branch instead of the latest release. I've moved to WarMenu because NativeUI was giving me a headache. See https://github.com/matsn0w/MISS-ELS/pull/120
