### ISSUE TITLE
ELS Issue

### ISSUE THREAD

**Issue by CharlieBurner** [matsn0w/MISS-ELS#153]
I have popped it inside my server and put it inside of my [Vehicles] Folder witch btw is inside of my .cfg file. And it does not work ( Does not show up on the servers resource list )

**Comment by matsn0w** [comment]
Hi there, have you read and followed the [installation instructions](https://github.com/matsn0w/MISS-ELS/blob/main/docs/installation.md) carefully? Note that you should not download the entire GitHub repository, just the `resource/` folder.
