### ISSUE TITLE
ELS switch on by all vehicles

### ISSUE THREAD

**Issue by CoDSaboteur** [matsn0w/MISS-ELS#154]
The ELS not working correct.as example someone of ambulance switch on the siren also the sirens turn on by people thats in a police car. So the sirens turn on, on more els vehicles.

is there a fix for?

**Comment by matsn0w** [comment]
Are you using OneSync? MISS-ELS is not compatible with OS (yet). Stay tuned, we are working on it!

Also see https://github.com/matsn0w/MISS-ELS/issues/36

**Comment by Merijn73** [comment]
yet any update on OneSync infinity?

**Comment by matsn0w** [comment]
> yet any update on OneSync infinity?

Not yet, we are working on it. In the meantime, you could use https://github.com/TheCoati/MIX-ELS by @TheCoati, which is a fork of MISS-ELS.
