### ISSUE TITLE
Phonetic Alphabet Issues with MISS-ELS

### ISSUE THREAD

**Issue by Kraslot2023** [matsn0w/MISS-ELS#156]
So I have purchased a dutch wm-serversirens pack. It uses Alpha to Hotel (the standard) those are working fine. But when it comes to India > Oscar the sirens are not working. Where do I need to look to change or is it so that after Hotel nothing is supported?

**Comment by TheCoati** [comment]
As far as I know, the WMServerSirens repository at https://github.com/Walsheyy/WMServerSirens only supports up to 8 sirens (up to SIREN_HOTEL).  \
There used to be a paywall version that granted additional siren slots, but I'm not sure if that version is still obtainable.

If you managed to acquire this "special" version of WMServerSirens, it should not pose an issue with MISS-ELS. \
MISS-ELS simply loads the AudioBank and plays the sound from the entity.

https://github.com/matsn0w/MISS-ELS/blob/1c393377c1e9f5447281af5d6fdb6d9d041b8eb2/resource/client/init.lua#L16

https://github.com/matsn0w/MISS-ELS/blob/1c393377c1e9f5447281af5d6fdb6d9d041b8eb2/resource/client/lights.lua#L121-L127

You can easily debug this with the following snippet:

```lua
Citizen.CreateThread(function()
    RequestScriptAudioBank('DLC_WMSIRENS\\SIRENPACK_ONE', false)
    
    local soundId = GetSoundId()
    local playerPed = PlayerPedId()
    
    -- Experiment with the SIREN_DELTA to test other tones
    PlaySoundFromEntity(soundId, 'SIREN_DELTA', playerPed, 'DLC_WMSIRENS_SOUNDSET', 0, 0)
    
    Citizen.Wait(5000)
    
    StopSound(ELSvehicle.sound)
    ReleaseSoundId(ELSvehicle.sound)
end)
```
