### ISSUE TITLE
They ban u if u say something

### ISSUE THREAD

**Issue by CoDSaboteur** [matsn0w/MISS-ELS#158]
WATCH OUT USEING THIS!!!!
Not onesync suported and the support is pore!!!! If u say something negative they will ban u.. I have a ban because say something about they promise alot and do nothing. So be aware this script not working correct and if u say something about it u will banned..

**Comment by TheCoati** [comment]
Your engagement and feedback are greatly appreciated. However, GitHub issues serve as a dedicated space for discussing specific aspects of the project, such as bugs, feature requests, or codebase improvements. Input from users like you is valuable, and it's important to ensure that discussions here remain closely tied to the project's development.

Understanding your concerns, open dialogue is encouraged. To ensure that feedback receives the attention it deserves, it is suggested to seek out a more suitable platform or community where discussions align with your interests or concerns in a more relevant context.

Focusing discussions here on project-related matters helps maintain an organized and productive environment for contributors and users.
