### ISSUE TITLE
They ban u and delete messages

### ISSUE THREAD

**Issue by CoDSaboteur** [matsn0w/MISS-ELS#159]
WATCH OUT WITH THIS!!!
The hole ELS not working correct and isnt onesync supported. If u say something about it they wil ban u or delete your messages.

They also promise for months now for a update that it works beter and onesync compitible. But its only words… If u say something about it they will ban u and delete all your messages. They wil 100% delete this to. But beware dont use this..

**Comment by TheCoati** [comment]
I noticed that you previously raised concerns in [this issue](https://github.com/matsn0w/MISS-ELS/issues/158), and I want to clarify that it's not deleted but rather closed to maintain the project.

I'd like to reiterate that GitHub may not be the appropriate platform for this type of discussion. 

I would also like to emphasize that this project is **open source**.
If you have specific features or improvements in mind, you are more than welcome to contribute and help implement them.

**Comment by CoDSaboteur** [comment]
“ GitHub may not be the appropriate platform for this type of discussion.”

Funny u say that……… Because this is the only place I not be banned. If u want to talk about it your send a ban.. so yes then people need to be discus it here. Your gays are banning everyone thats says something

**Comment by TheCoati** [comment]
I need to emphasize that this is not the appropriate platform for repetitive discussions, especially if you have been banned from another related medium. There are likely valid reasons for such actions, and GitHub issues should not be used as a place to air grievances.

This resource is a collaborative effort by volunteers to maintain a codebase, and we encourage a positive and productive environment. If this resource doesn't align with your needs or requirements, you have the option to contribute to the project or explore other resources that better suit your needs.

I must also address the tone of your recent comments, which has become increasingly inappropriate and immature. I urge you to review GitHub's terms of service (https://docs.github.com/en/site-policy/github-terms/github-terms-of-service) for guidance on acceptable conduct and communication within this community. Lets maintain professionalism and respect for one another.

**Comment by CoDSaboteur** [comment]
Sorry u can send what u want. I been mot rude or say annything bad. I say only wet is is, on a normal tune and do nothing wrong. So u can send policy what u want but do nothing wrong. If u cutt off all communication dont complain here I set a message here..
