### ISSUE TITLE
Sirens distance

### ISSUE THREAD

**Issue by m1zer1337** [matsn0w/MISS-ELS#160]
I have discovered that if I turn on my sirens, other people on the server hear the sirens as if the sound was coming from their vehicle no matter the distance. It seams like the distance sync doesent work

**Comment by matsn0w** [comment]
Hi, thank you for posting your issue. This problem is caused by OneSync. Currently, OneSync is not supported by MISS-ELS. We are working on that, but I can't give you an ETA for that.

See https://github.com/matsn0w/MISS-ELS/issues/36
