### ISSUE TITLE
Sirens enable on all vehicles when one person enables them

### ISSUE THREAD

**Issue by Kunodo** [matsn0w/MISS-ELS#161]
**Describe the bug**
When one person enables their sirens, it enables them on all other els vehicles as well. This doesnt happen with any of the lights or signs.

**To Reproduce**
Enable the siren when a little distance away from other people in els cars.

**Additional context**
FiveM build: b2189
MISS ELS version: 2.1.1

**Comment by matsn0w** [comment]
This is probably because of OneSync. See https://github.com/matsn0w/MISS-ELS/issues/36
