### ISSUE TITLE
Els randomly stops working

### ISSUE THREAD

**Issue by radomyoung** [matsn0w/MISS-ELS#35]
Evening 

while using ELS inside fivem it randomly stops the script until you restart it manually .

only error codes we get is below 

[   1383594] [b2189_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @ELS/client/main.lua:39: attempt to index a nil value (field '?')^7
[   1383594] [b2189_GTAProce]             MainThrd/ ^3> HandleHorn^7 (^5@ELS/client/main.lua^7:39)
[   1383594] [b2189_GTAProce]             MainThrd/ ^3> fn^7 (^5@ELS/client/main.lua^7:170)

nothing has changed and been dropped into the server as it is in the install.

also I do believe there is a newer version but that one doesn’t work with the server for us if there’s any help with that as well .

many thanks

**Comment by callum1337** [comment]
+1

**Comment by matsn0w** [comment]
Hey, thank you for your issue!

I've seen this error a couple times myself. Not sure what's causing it at the moment, I will investigate it.

> also I do believe there is a newer version but that one doesn’t work with the server for us if there’s any help with that as well .

I'm sorry, what do you mean? What doesn't work?

**Comment by radomyoung** [comment]
So from what i seen the version i have currently to whats on github is different but when we try to install the new one it dosen't load for us and when we resort back to the previous version it that works straight away .

**Comment by matsn0w** [comment]
Ah, how did you download the resource? Please download the latest release [from here](https://github.com/matsn0w/MISS-ELS/releases/latest) (under Assets) and do not download the source code directly.

I've restructured the code to reduce the size this resource would occupy on the server.

**Comment by radomyoung** [comment]
![image](https://user-images.githubusercontent.com/97453568/150007160-ae3c6338-c609-4a58-adda-107e908c4a33.png)


Our ELS is now stopping with these errors

**Comment by matsn0w** [comment]
That's a parse error from the XML library. That means that one of your VCF's is invalid. Have you missed a `<` or a `>` somewhere?

**Comment by clapham** [comment]
> That's a parse error from the XML library. That means that one of your VCF's is invalid. Have you missed a `<` or a `>` somewhere?

there was 2 files in xmls that was bad

**Comment by radomyoung** [comment]
![image](https://user-images.githubusercontent.com/97453568/150702478-ee824acd-37c8-4867-8251-fe5eba5c621e.png)
so this is the current error at the moment. We can cycle through the sirens but when we get to the end instead of looping back around it crashes els.

**Comment by radomyoung** [comment]
![image](https://user-images.githubusercontent.com/97453568/150702650-656091e3-e389-4ca4-83a5-086188312524.png)

**Comment by matsn0w** [comment]
@radomyoung can you provide your VCF so I can reproduce this issue?

**Comment by radomyoung** [comment]
attached . i copied the Example server sirens vcf to use if this helps

**Comment by matsn0w** [comment]
All issues listed in this issue should be fixed now! You can use `develop` to test.
