### ISSUE TITLE
els freezes and we can not turn it off or on and error comes up

### ISSUE THREAD

**Issue by clapham** [matsn0w/MISS-ELS#38]
We get the error main.lua it crashes on the server everyones els and doesnt work again until you reset it.
![siren error](https://user-images.githubusercontent.com/90931247/150347305-94d10ba7-8184-4321-9298-f0712c73ef85.PNG)

client/main.lua:123 
>next siren client/main.lua :123 
>fn client/main.lua : 227

**Comment by matsn0w** [comment]
Same issue as #35, I'm still investigating this. Planning to fix this before the final release of v2.0.0.

Thank you for reporting!

**Comment by clapham** [comment]
so do you not know what it is dude? 
what time scale you looking as cannot use any els?
thnaks.

**Comment by clapham** [comment]
hi, so i have done some more testing the key bindings for keyboard and ELS for the keyboard works fine no errors no problems no crashing or anything. but if you use the controller to cycle through the sirens by pressing B once you get to the fourth siren it just freezes lights still flashing and the fourth siren playing and you can not switch them off again until you restart ELS resource.
i am guessing its a loop issue with controller support does in the main it not have to say if on srntone4=then 0 when press or something?

**Comment by matsn0w** [comment]
Ah, I see. Can you provide your VCF please?

**Comment by matsn0w** [comment]
Got it! Found the issue, it was trying 'siren 5', but that obviously doesn't exist. Fix coming in!

**Comment by clapham** [comment]
how do i download it again? or do we need to just change our coding to what you have there

**Comment by matsn0w** [comment]
You can download the latest version of the `develop` branch or wait untill the next (pre) release. The resource itself is in the `resource/` folder!

![image](https://user-images.githubusercontent.com/15019582/150847051-19e3f65a-1aa1-4d01-b0d2-135f53a76acd.png)
