### ISSUE TITLE
Add extra toggles for static extra's

### ISSUE THREAD

**Issue by matsn0w** [matsn0w/MISS-ELS#5]
Would be nice if there was an option to define 'static' extra's, like for takedown lights, that you can map to a specific key.

Maybe something like:

```xml
<Extra12 IsElsControlled="true" AllowEnvLight="true" Color="white" Static="true" Key="159" />
``` 

The `Key` option is a nice to have anyway. That'd allow mapping keys per vehicle instead of globally.

**Comment by matsn0w** [comment]
Adding the extra without env lights enabled is also very nice to have, for toggling static objects other than lights.

**Comment by ImperiousTT** [comment]
Make a NativeUI menu where the lights will be toggled, with the ability to enter specific text for a specific extra to make it customizable. e.g.:

Firetruck24
"White bright lights" -> Extra 11
"roller shutters" -> Extra 12

**Comment by matsn0w** [comment]
> 

Great idea! I think that's indeed the best way to do it, as it would require a lot of keybinds otherwise.... Will post an update soon!

**Comment by matsn0w** [comment]
Now look at that! Coming soon in #33!

![image](https://user-images.githubusercontent.com/15019582/149641990-1dc1dfc5-bc2f-4c6f-8d03-74f0910a65b2.png)
