### ISSUE TITLE
Statics menu only opens after restarting the resource

### ISSUE THREAD

**Issue by PerVanHassel** [matsn0w/MISS-ELS#63]
Sometimes when using the ELS, it bugs and the U menu doesn't open. but when i restart the script then it works. it doenst show a error in console iether

**Comment by matsn0w** [comment]
Hi, thank you for reporting this! 

I am experiencing this myself in our server, but not on my local test server. So I thought this problem was with our server, but apparently this is more common. I'm going to mark this as a bug and find out what's causing it. I'll get back to you later!

**Comment by PerVanHassel** [comment]
Sometimes the whole Els just stops too, thanks for looking into it btw!

**Comment by matsn0w** [comment]
@PerVanHassel here's a small update, I figured out that this is probably caused by a mismatch between multiple NativeUI installations.

In our server, we had a script that served a copy of NUI. Removing this and just relying on the standalone NUI resource fixed the issue for us.

Do you have any other scripts running NUI?

**Comment by PerVanHassel** [comment]
We have a home menu running on NativeUI yes

**Comment by matsn0w** [comment]
Ok. You might wanna try disabling that - does that make any difference?

**Comment by PerVanHassel** [comment]
The whole home menu or NativeUI

**Comment by PerVanHassel** [comment]
If i stop the home menu, the static menu indeed works better. Is there a way to fix that i dont have to stop the home menu? So that i can run 2 resource's with NativeUI and not have the ELS buggin

**Comment by matsn0w** [comment]
Not sure why it is not working properly, I guess there's an issue with running multiple 'instances' of NUI. I managed to fix it by removing the hard dependency from the other menu and instead rely on a standalone installation of NUI. 

What menu is it? Did you write it yourself?

**Comment by matsn0w** [comment]
Marking this issue as 'invalid' as it seems that this issue is not caused by this resource.
