### ISSUE TITLE
Feature: add headlight wig wags

### ISSUE THREAD

**Issue by Drillz244** [matsn0w/MISS-ELS#70]
Wig wags to be enabled like this https://youtu.be/Knd50CXadzA and be supported .

**Comment by matsn0w** [comment]
Thank you! I'll take a look at this, see if this can be implemented and whether that looks a bit realistic.

**Comment by matsn0w** [comment]
I've added a feature that allows flashing the high beam of the headlights. I'm afraid alternating between left and right isn't a thing right now.
