### ISSUE TITLE
[Configurator] Extra ID's have no leading 0

### ISSUE THREAD

**Issue by matsn0w** [matsn0w/MISS-ELS#71]
VCF's exported by the Configurator are missing a leading zero in their name.

They are now `<Extra1 />` for example, which should be `<Extra01 />` as the script reads the last characters from the right.

Either fix this in the configurator or take this edge case into account when parsing the XML.

*This issue was reported by Gunny Hartman#4134 via my [Discord server](https://matsn0w.dev/discord)*

**Comment by matsn0w** [comment]
Partially fixed by @JustinRijsdijk in #72, issue can be closed when the VCF parser takes not having a leading zero into account.

**Comment by JustinRijsdijk** [comment]
Parser fix will be on tonight
