### ISSUE TITLE
Feature: allow toggling extras for attached trailers

### ISSUE THREAD

**Issue by ImperiousTT** [matsn0w/MISS-ELS#80]
Hey, I was wondering if it is possible to enable the extra's of a trailer, while the player is in the vehicle towing it, without interfering with the vehicles extra's.
A great example of the use would be something like this:
![image](https://user-images.githubusercontent.com/47085980/154997956-ecd4cd3d-33da-4ca8-a109-14b5fd9fcef6.png)

**Comment by matsn0w** [comment]
https://docs.fivem.net/natives/?_0x1CDD6BADC297830D

**Comment by matsn0w** [comment]
Tried retrieving the vehicle with above method and then setting an extra on it. This does sadly enough not work. `DoesExtraExist()` returns `false`.

**Comment by matsn0w** [comment]
Closing this for now.
