### ISSUE TITLE
Emergency state on all light patterns

### ISSUE THREAD

**Issue by ImperiousTT** [matsn0w/MISS-ELS#81]
AI traffic now treats each light stage as an emergency state, which makes them move to the sides.
However, it would be nice to configure that in the XML which light stage should toggle the emergency state. 

For example, the 'STOP' signs / Traffic Advisors etc should not cause traffic to get out of their path to let the vehicle pass.
![image](https://user-images.githubusercontent.com/47085980/154999247-af2270bc-a1f1-425d-a665-79768185f5df.png)

**Comment by matsn0w** [comment]
Hey, that's already possible!

See https://github.com/matsn0w/MISS-ELS/blob/main/docs/vcf.md#patterns-pattern
