### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by SchiriLuca** [matsn0w/MISS-ELS#91]
Alle Spieler die in einem Fahrzeug sitzen hören das Martinshorn obwohl nur einer es an hat wie kann ich das Reparieren

**Comment by matsn0w** [comment]
I'm sorry, what do you mean with the Martinshorn?

**Comment by SchiriLuca** [comment]
ich meine die Sirene

**Comment by SchiriLuca** [comment]
Wenn ich bei mir auf dem Server in einem Polizeiauto Blaulicht und Sirene anmache hören es alle anderen die auch in einem Polizeiauto sitzen

**Comment by matsn0w** [comment]
Ok, so you mean that everyone's siren is toggled instead of just one's. 

Are you using OneSync?

**Comment by matsn0w** [comment]
Closed for inactivity.
